### ISSUE TITLE
RedhatVersionAcceptor doesn't accept "-redhat-" version

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/maven-vbe#1]
https://github.com/jboss-set/maven-vbe/blob/master/src/main/java/org/jboss/set/maven/release/extension/version/RedhatVersionAcceptor.java#L7

`-redhat-` is also a valid redhat productized version.

**Comment by baranowb** [comment]
yes, its by design, to purge fuser-99999-redhat-
