### ISSUE TITLE
fetchDependencyMetadata() has been called twice ?

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/maven-vbe#3]
It seems second `fetchDependencyMetadata()` is redundant at https://github.com/jboss-set/maven-vbe/blob/master/src/main/java/org/jboss/set/maven/release/extension/VersionBumpExtension.java#L224-L236

**Comment by baranowb** [comment]
lol

**Comment by soul2zimate** [comment]
I saw the second one is removed, but the two logs seem duplicate. I guess you only want one when `results == null || results.size() == 0` is `true`

**Comment by soul2zimate** [comment]
fixed by https://github.com/jboss-set/maven-vbe/commit/e7d399928190d0dc204d707e79ec2ce7777ba967
